# Site settings
title: Fabian Schultz
description: My new site!
url: ""
permalink: pretty

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path

# Plugins
plugins: [jekyll-typogrify, jekyll-assets]

assets:
  digest: true
  debug: true
  sources:
    - "_assets/css"
    - "_assets/js"

# Build settings
markdown: kramdown
exclude: ["node_modules", "Gemfile", "Gemfile.lock", "package.json", "scripts", "postcss.config.js", "CNAME"]
